name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        include: "Jwt.cs"
        find: "SUPERSECRETPLACEHOLDER"
        replace: "${{ secrets.JWTTOKEN }}"
        regex: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -c Release
    - name: release
      uses: zendesk/action-create-release@v1
      id: create_release
      with:
        tag_name: Latest
        release_name: Latest
        draft: false
        prerelease: false
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "bin/Release/net6.0/linux-x64/publish/rich-presence-linux"
        asset_name: "rich-presence-linux"
        asset_content_type: application/octet-stream
      
